### PR TITLE
benchmarking framework

### PR DESCRIPTION
**Pull request by WilsonGregory**
## Changes
- start working on benchmark framework
- basically the idea is each model has a function getBenchmark that incorporates the parameters and returns a function that initializes the model, trains it, and gets the markers based on a combination of the original provided parameters and the parameter that we are benchmarking over
- all the models are then provided to the benchmarking function runs all models on the data and ranges over the benchmarking range value, which is so far just k
- add a plotting function that takes the output of benchmarking and plots it nicely
- Followup: implement getBenchmark for all the other models. This will involve making our own wrapper classes for stuff like smashpy and lassonet
- Followup: implement other kinds of benchmarking, like percent data mislabeled

## Testing
- ran the benchmark_k script, among other tests
- unit tests for the plot function

## Doc Changes
- update readme with a short description, will be fleshed out with examples in a followup

## Plots
image
image

### CODE REVIEW

**Comment by beelze-b** [comment]
This looks great. Seems like high level wrappers on the existing code. Not sure if I said it but this reminds me to mention that we can't directly numpy.save the results of `new_model_metrics` because it includes nested tuples which is deprecated in the future. I guess it is more accurate to say that we can save it but should change the behavior in the notebooks.

I notice that these scripts save the results in a different way, but `benchmark` does not store the confusion matrices or the F1/Precision scores. Are those metrics being evaluated elsewhere, or are we rethinking what metrics to calculate?

**Review by beelze-b — APPROVED** [review]
I approve these changes. No modification to existing code and just adding better ways to use it. Have questions on storing the `test_rep` which is the classification_report on the test set and the `cm` which is the confusion matrix.

**Comment by beelze-b** [comment]
Also sorry for the delay in getting to this review.

**Comment by WilsonGregory** [comment]
Yup, mostly high level wrappers on the models. You make a good point about the confusion matrices and F1, or precision, or what have you. My main goal here was to get the accuracy plots aggregating a bunch of models. But really, the benchmark function should return all that output of the classification report and the confusion matrices, then in the plot function you should be able to specify different metrics to compare, like accuracy, or misclass rate, or F1, and so on (I also want to do training time).

I haven't thought about saving at all. I have just been running models locally, but when I start running them on a cluster or something that will be key.

**Pull request merged**
